# Generated by Django 5.2.7 on 2026-09-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('technologies', models.TextField(help_text='Comma-separated list of technologies, frameworks, and tools used')),
                ('outcomes', models.TextField(help_text='Measurable impact, metrics, or project deliverables')),
                ('duration_months', models.IntegerField(default=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_project', models.CharField(default='Core Contributor', max_length=150)),
                ('contribution_summary', models.TextField()),
                ('evidence', models.TextField(blank=True, default='', help_text='Concrete artifact/impact evidence for skill inference')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='employees.employee')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'project')},
            },
        ),
    ]
