# Generated by Django 5.2.7 on 2026-09-19 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('employees', '0002_employee_availability_pct_and_more'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ai_processing_mode',
            field=models.CharField(choices=[('AI_ALLOWED', 'AI Allowed (Full Context)'), ('AI_SAFE_SUMMARY', 'AI-Safe Summary Only (Redacted)'), ('NO_EXTERNAL_AI', 'No External AI Processing')], default='AI_ALLOWED', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security'), ('Healthcare Analytics', 'Healthcare Analytics'), ('Financial Technology', 'Financial Technology')], default='Engineering', max_length=60),
        ),
        migrations.AddField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.enterprise'),
        ),
        migrations.AddField(
            model_name='project',
            name='objective',
            field=models.TextField(blank=True, default='', help_text='Strategic business objective or goal of the project'),
        ),
        migrations.AddField(
            model_name='project',
            name='required_skills',
            field=models.TextField(blank=True, default='', help_text='Comma-separated or list of required skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='sensitivity_level',
            field=models.CharField(choices=[('HR_ONLY', 'HR Only (Confidential / Sensitive)'), ('HR_CONTRIBUTORS', 'HR + Assigned Contributors'), ('ENTERPRISE_PUBLIC', 'Enterprise Public')], default='ENTERPRISE_PUBLIC', max_length=30),
        ),
        migrations.AddField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Staffing', 'Staffing'), ('Active', 'Active'), ('Completed', 'Completed'), ('Archived', 'Archived')], default='Active', max_length=30),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='allocation_pct',
            field=models.FloatField(default=0.5, help_text='Time commitment percentage on this project'),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='technologies_demonstrated',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending HR Review'), ('approved', 'Approved / HR-Verified'), ('rejected', 'Rejected')], default='approved', max_length=30),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectcontribution',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='project',
            name='outcomes',
            field=models.TextField(blank=True, default='', help_text='Measurable impact, metrics, or project deliverables'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('enterprise', 'name')},
        ),
        migrations.CreateModel(
            name='StaffingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=200)),
                ('department', models.CharField(default='Engineering', max_length=60)),
                ('team_size', models.IntegerField(default=5)),
                ('required_skills', models.JSONField(default=list, help_text='List of skill requirements with proficiency & importance')),
                ('minimum_experience', models.FloatField(default=2.0)),
                ('duration_months', models.IntegerField(default=3)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Staffed', 'Staffed'), ('Cancelled', 'Cancelled')], default='Open', max_length=30)),
                ('weights_config', models.JSONField(blank=True, default=dict, help_text='Custom weights configuration for staffing ranking')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enterprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_requests', to='core.enterprise')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staffing_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_staffing', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffingRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0.0)),
                ('skill_score', models.FloatField(default=0.0)),
                ('experience_score', models.FloatField(default=0.0)),
                ('project_score', models.FloatField(default=0.0)),
                ('evidence_score', models.FloatField(default=0.0)),
                ('freshness_score', models.FloatField(default=0.0)),
                ('availability_score', models.FloatField(default=0.0)),
                ('matched_skills', models.JSONField(default=list)),
                ('missing_skills', models.JSONField(default=list)),
                ('explanation', models.TextField(blank=True, default='')),
                ('rank', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Recommended', 'Recommended'), ('Assigned', 'Assigned'), ('Declined', 'Declined'), ('Deferred', 'Deferred')], default='Recommended', max_length=30)),
                ('feedback_reason', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffing_recommendations', to='employees.employee')),
                ('staffing_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='projects.staffingrequest')),
            ],
            options={
                'ordering': ['rank', '-overall_score'],
                'unique_together': {('staffing_request', 'employee')},
            },
        ),
    ]
