# Generated by Django 5.2.7 on 2026-09-19 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_created_at_and_more'),
        ('employees', '0003_alter_employeeskill_confidence_and_more'),
        ('projects', '0002_project_ai_processing_mode_project_created_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security'), ('Healthcare Analytics', 'Healthcare Analytics'), ('Financial Technology', 'Financial Technology')], db_index=True, default='Engineering', max_length=60),
        ),
        migrations.AlterField(
            model_name='project',
            name='sensitivity_level',
            field=models.CharField(choices=[('HR_ONLY', 'HR Only (Confidential / Sensitive)'), ('HR_CONTRIBUTORS', 'HR + Assigned Contributors'), ('ENTERPRISE_PUBLIC', 'Enterprise Public')], db_index=True, default='ENTERPRISE_PUBLIC', max_length=30),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Proposed', 'Proposed'), ('Staffing', 'Staffing'), ('Active', 'Active'), ('Completed', 'Completed'), ('Archived', 'Archived')], db_index=True, default='Active', max_length=30),
        ),
        migrations.AlterField(
            model_name='projectcontribution',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending HR Review'), ('approved', 'Approved / HR-Verified'), ('rejected', 'Rejected')], db_index=True, default='approved', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffingrecommendation',
            name='overall_score',
            field=models.FloatField(db_index=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='staffingrecommendation',
            name='rank',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='staffingrecommendation',
            name='status',
            field=models.CharField(choices=[('Recommended', 'Recommended'), ('Assigned', 'Assigned'), ('Declined', 'Declined'), ('Deferred', 'Deferred')], db_index=True, default='Recommended', max_length=30),
        ),
        migrations.AlterField(
            model_name='staffingrequest',
            name='department',
            field=models.CharField(db_index=True, default='Engineering', max_length=60),
        ),
        migrations.AlterField(
            model_name='staffingrequest',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Staffed', 'Staffed'), ('Cancelled', 'Cancelled')], db_index=True, default='Open', max_length=30),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['enterprise', 'status'], name='projects_pr_enterpr_0df1e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['enterprise', 'sensitivity_level'], name='projects_pr_enterpr_de1b94_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcontribution',
            index=models.Index(fields=['employee', 'verification_status'], name='projects_pr_employe_3e1a8c_idx'),
        ),
        migrations.AddIndex(
            model_name='projectcontribution',
            index=models.Index(fields=['project', 'verification_status'], name='projects_pr_project_679099_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingrecommendation',
            index=models.Index(fields=['staffing_request', 'rank'], name='projects_st_staffin_89e7b7_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingrecommendation',
            index=models.Index(fields=['staffing_request', 'status'], name='projects_st_staffin_41cdf6_idx'),
        ),
        migrations.AddIndex(
            model_name='staffingrequest',
            index=models.Index(fields=['enterprise', 'status'], name='projects_st_enterpr_7b405b_idx'),
        ),
    ]
