# Generated by Django 5.2.7 on 2026-09-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security')], default='Engineering', max_length=60)),
                ('description', models.TextField()),
                ('responsibilities', models.TextField(help_text='Detailed key responsibilities and expectations')),
                ('required_experience_years', models.FloatField(default=3.0)),
                ('future_demand_level', models.CharField(choices=[('Critical', 'Critical Growth Need'), ('High', 'High Demand'), ('Moderate', 'Moderate Demand')], default='High', max_length=20)),
                ('embedding', models.JSONField(blank=True, help_text='Cached embedding vector for semantic matching', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RoleSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('Essential', 'Essential (Core Requirement)'), ('Preferred', 'Preferred (High Value)'), ('Nice-to-have', 'Nice-to-have (Bonus)')], default='Essential', max_length=20)),
                ('minimum_proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=20)),
                ('is_required', models.BooleanField(default=True, help_text='Whether this skill is strictly mandatory for the role')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_skills', to='roles.role')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_requirements', to='skills.skill')),
            ],
            options={
                'ordering': ['-is_required', 'skill__name'],
                'unique_together': {('role', 'skill')},
            },
        ),
    ]
