# Generated by Django 5.2.7 on 2026-09-19 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_created_at_and_more'),
        ('roles', '0002_role_enterprise_role_is_active_alter_role_department_and_more'),
        ('skills', '0002_skill_enterprise_alter_skill_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security'), ('Healthcare Analytics', 'Healthcare Analytics'), ('Financial Technology', 'Financial Technology')], db_index=True, default='Engineering', max_length=60),
        ),
        migrations.AlterField(
            model_name='role',
            name='future_demand_level',
            field=models.CharField(choices=[('Critical', 'Critical Growth Need'), ('High', 'High Demand'), ('Moderate', 'Moderate Demand')], db_index=True, default='High', max_length=20),
        ),
        migrations.AlterField(
            model_name='role',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='roleskill',
            name='importance',
            field=models.CharField(choices=[('Essential', 'Essential (Core Requirement)'), ('Preferred', 'Preferred (High Value)'), ('Nice-to-have', 'Nice-to-have (Bonus)')], db_index=True, default='Essential', max_length=20),
        ),
        migrations.AlterField(
            model_name='roleskill',
            name='is_required',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether this skill is strictly mandatory for the role'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['enterprise', 'is_active'], name='roles_role_enterpr_4dc11c_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['department', 'future_demand_level'], name='roles_role_departm_4b0e30_idx'),
        ),
        migrations.AddIndex(
            model_name='roleskill',
            index=models.Index(fields=['role', 'is_required'], name='roles_roles_role_id_6c1f0e_idx'),
        ),
        migrations.AddIndex(
            model_name='roleskill',
            index=models.Index(fields=['skill', 'importance'], name='roles_roles_skill_i_b8e4a3_idx'),
        ),
    ]
