# Generated by Django 5.2.7 on 2026-09-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('provider', models.CharField(choices=[('Internal Academy', 'TalentGraph Internal Academy'), ('Coursera', 'Coursera Enterprise'), ('AWS Skill Builder', 'AWS Skill Builder'), ('Google Cloud Skills', 'Google Cloud Skills Boost'), ("O'Reilly", "O'Reilly Media"), ('DeepLearning.AI', 'DeepLearning.AI'), ('Linux Foundation', 'Linux Foundation')], default='Internal Academy', max_length=100)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Intermediate', max_length=20)),
                ('duration_hours', models.IntegerField(default=10)),
                ('certification_name', models.CharField(blank=True, default='', max_length=200)),
                ('url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('skills_covered', models.ManyToManyField(related_name='learning_resources', to='skills.skill')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeLearning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='In Progress', max_length=20)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('outcome', models.TextField(blank=True, default='', help_text='Assessment score or capstone project evidence')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learnings', to='employees.employee')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='learning.learningresource')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('employee', 'resource')},
            },
        ),
    ]
