# Generated by Django 5.2.7 on 2026-09-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningresource',
            name='enterprise',
            field=models.ForeignKey(blank=True, help_text='Null for global learning catalog, set for enterprise-specific courses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_resources', to='core.enterprise'),
        ),
    ]
