# Generated by Django 5.2.7 on 2026-09-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('RoleMatch', 'Role Recommendation Match'), ('Learning', 'Learning Resource Recommendation'), ('Roadmap', 'Career Development Roadmap'), ('SkillInference', 'AI-Discovered Skill')], default='RoleMatch', max_length=30)),
                ('accepted', models.BooleanField(default=True, help_text='True for accepted/liked, False for rejected/disliked')),
                ('reason', models.TextField(blank=True, default='', help_text='Employee feedback rationale or context')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='employees.employee')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='roles.role')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
