# Generated by Django 5.2.7 on 2026-09-19 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('department', models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security')], default='Engineering', max_length=60)),
                ('current_role', models.CharField(max_length=150)),
                ('years_experience', models.FloatField(default=1.0)),
                ('education', models.CharField(blank=True, default='', max_length=255)),
                ('certifications', models.TextField(blank=True, default='', help_text='Comma-separated or newline list of certifications')),
                ('bio', models.TextField(blank=True, default='')),
                ('interests', models.TextField(blank=True, default='', help_text='Areas of career curiosity or aspirational interests')),
                ('avatar_url', models.URLField(blank=True, default='')),
                ('embedding', models.JSONField(blank=True, help_text='Cached embedding vector', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CareerGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_role_title', models.CharField(max_length=150)),
                ('target_role_id', models.IntegerField(blank=True, help_text='Optional FK reference to Role id', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='career_goal', to='employees.employee')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], default='Intermediate', max_length=20)),
                ('confidence', models.FloatField(default=0.85, help_text='Confidence score between 0.0 and 1.0')),
                ('source', models.CharField(choices=[('explicit', 'Explicit (Self-Reported / Verified)'), ('project_inferred', 'Project-Inferred'), ('learning', 'Learning & Certification'), ('ai_discovered', 'AI-Discovered (Hidden/Transferable)')], default='explicit', max_length=30)),
                ('evidence', models.TextField(blank=True, default='', help_text='Mandatory grounding context for inferred/discovered skills')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='employees.employee')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_proficiencies', to='skills.skill')),
            ],
            options={
                'ordering': ['-confidence', 'skill__name'],
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
