# Generated by Django 5.2.7 on 2026-09-19 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='availability_pct',
            field=models.FloatField(default=1.0, help_text='Current capacity available for project staffing (0.0 to 1.0)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='current_allocation_pct',
            field=models.FloatField(default=0.0, help_text='Allocated capacity across active projects'),
        ),
        migrations.AddField(
            model_name='employee',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='core.enterprise'),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='last_demonstrated_date',
            field=models.DateField(blank=True, help_text='Date when skill was most recently practiced', null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='verification_status',
            field=models.CharField(choices=[('self_reported', 'Self-Reported'), ('hr_verified', 'HR Verified'), ('ai_inferred', 'AI Inferred'), ('system_generated', 'System Generated')], default='hr_verified', max_length=30),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeeskill',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_employee_skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('AI Research', 'AI Research & Platform'), ('Data Platform', 'Data Platform & Analytics'), ('Cloud Architecture', 'Cloud & Infrastructure'), ('Product', 'Product & Design'), ('Security', 'Information Security'), ('Healthcare Analytics', 'Healthcare Analytics'), ('Financial Technology', 'Financial Technology')], default='Engineering', max_length=60),
        ),
    ]
