# Generated by Django 5.2.7 on 2026-09-19 07:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_approvalrequest_created_at_and_more'),
        ('employees', '0002_employee_availability_pct_and_more'),
        ('skills', '0002_skill_enterprise_alter_skill_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeskill',
            name='confidence',
            field=models.FloatField(db_index=True, default=0.85, help_text='Confidence score between 0.0 and 1.0'),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='proficiency',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Expert', 'Expert')], db_index=True, default='Intermediate', max_length=20),
        ),
        migrations.AlterField(
            model_name='employeeskill',
            name='verification_status',
            field=models.CharField(choices=[('self_reported', 'Self-Reported'), ('hr_verified', 'HR Verified'), ('ai_inferred', 'AI Inferred'), ('system_generated', 'System Generated')], db_index=True, default='hr_verified', max_length=30),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['enterprise', 'department'], name='employees_e_enterpr_20912e_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['enterprise', 'availability_pct'], name='employees_e_enterpr_a0a875_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['created_at'], name='employees_e_created_52c8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['employee', 'verification_status'], name='employees_e_employe_a88829_idx'),
        ),
        migrations.AddIndex(
            model_name='employeeskill',
            index=models.Index(fields=['skill', 'confidence'], name='employees_e_skill_i_46072b_idx'),
        ),
    ]
