# Generated by Django 5.2.7 on 2026-09-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120, unique=True)),
                ('category', models.CharField(choices=[('AI/ML', 'Artificial Intelligence & Machine Learning'), ('Backend', 'Backend & Distributed Systems'), ('Frontend', 'Frontend & Mobile Engineering'), ('Data Engineering', 'Data Engineering & Analytics'), ('Cloud & DevOps', 'Cloud, Infrastructure & DevOps'), ('Security', 'Cybersecurity & Governance'), ('Leadership & Product', 'Leadership, Strategy & Product')], default='Backend', max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('market_trend', models.CharField(choices=[('Critical', 'Critical High Growth'), ('Growing', 'Growing Demand'), ('Stable', 'Stable Core Skill')], default='Growing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
