# Generated by Django 5.2.7 on 2026-09-19 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='enterprise',
            field=models.ForeignKey(blank=True, help_text='Null for global common taxonomy skills, set for enterprise-custom skills', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_skills', to='core.enterprise'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(db_index=True, max_length=120),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('enterprise', 'name')},
        ),
    ]
